# Generated by Django 4.1.6 on 2023-02-11 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boston_construction", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="constructionrecord",
            name="address_1",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="constructionrecord",
            name="address_2",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="constructionrecord",
            name="construction_notes",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="constructionrecord",
            name="contact_number",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="constructionrecord",
            name="contractor",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="constructionrecord",
            name="district",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="constructionrecord",
            name="estimated_completion_date",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="constructionrecord",
            name="expiration_date",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="constructionrecord",
            name="intersection",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="constructionrecord",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="constructionrecord",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="constructionrecord",
            name="neighborhood",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="constructionrecord",
            name="number_of_works",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="constructionrecord",
            name="permit",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="constructionrecord",
            name="permittee",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="constructionrecord",
            name="project_category",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="constructionrecord",
            name="roadway_plates_in_use",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="constructionrecord",
            name="sidewalk_plates_in_use",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="constructionrecord",
            name="start",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="constructionrecord",
            name="status",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="constructionrecord",
            name="street",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="constructionrecord",
            name="to",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="constructionrecord",
            name="trench_length",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="constructionrecord",
            name="work_schedule",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
