# Generated by Django 4.1.6 on 2023-02-12 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boston_construction", "0002_alter_constructionrecord_address_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="constructionrecord",
            name="zip_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="mailinglistrecord",
            name="email",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="mailinglistrecord",
            name="secret",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
