# Generated by Django 4.1.6 on 2023-02-12 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boston_construction", "0003_constructionrecord_zip_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="constructionrecord",
            name="estimated_completion_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="constructionrecord",
            name="expiration_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
