# Generated by Django 4.1.6 on 2023-02-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "boston_construction",
            "0004_alter_constructionrecord_estimated_completion_date_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.TextField()),
                ("was_executed_before", models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name="mailinglistrecord",
            name="email",
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
